- name: Installation de NGINX pour le TP
  hosts: all
  become: yes
  tasks:
    - name: Mise a jour du cache APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer NGINX
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Demarrer et activer NGINX
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
